baseURL = "http://example.org/"
languageCode = "en-us"
language = "en"
title = "Alexander's Blog"
author = "Alexander Lyon"
theme = "CAPSLOCK"

sectionPagesMenu = "main"
pygmentsCodeFences = true
pygmentsOptions="linenos=inline"
pygmentsStyle="bw"
paginate=2