baseURL = "https://blog.arlyon.dev/"
languageCode = "en-us"
language = "en"
title = "Alex's Thoughts"
author = "Alexander Lyon"

# Theme Settings

theme = "CAPSLOCK"

googleAnalytics = "UA-55373202-3"
enableRobotsTXT = true
enableGitInfo = true
sectionPagesMenu = "main"
pygmentsOptions = "linenos=table"
pygmentsStyle = "bw"
pygmentsUseClasses = true
pygmentsCodeFences = true

[params]
    description = "Useful explanations, code snippets, and projects gathered from a wide range of areas in computer science."
    show_read_time = true
    service_worker = false
    show_contact_in_head = false
    show_contact_in_footer = true
    fontawesome_kit = "fd8ad81501"
    copyright = "alexander lyon © no monkeys (or typewriters) were harmed in the making of this site"
    foreground = "#000"

[[params.contact]]
    icon_type = "fab"
    icon_name = "github"
    link = "https://www.github.com/arlyon/"
    text = "github"

[[params.contact]]
    icon_type = "fab"
    icon_name = "gitlab"
    link = "https://www.gitlab.com/arlyon/"
    text = "gitlab"

[[params.contact]]
    icon_type = "fab"
    icon_name = "reddit"
    link = "https://www.reddit.com/u/alexthelyon/"
    text = "reddit"

[[params.contact]]
    icon_type = "fas"
    icon_name = "file-certificate"
    link = "https://www.reddit.com/u/alexthelyon/"
    text = "cv"

[outputs]
    home = [ "HTML", "RSS", "HEADERS" ]
    page = [ "HTML" ]

[mediaTypes]
    [mediaTypes."text/netlify"]
    suffixes = [""]
    delimiter = ""

[outputFormats]
    [outputFormats.HEADERS]
    mediatype = "text/netlify"
    baseName = "_headers"
    isPlainText = true
    notAlternative = true
